/*
	Copyright 2026, Philip Rose, GM3ZZA

	This file is part of ZZACWT: ZZA CW Trainer.

	ZZACWT is free software: you can redistribute it and/or modify it under the
	terms of the Lesser GNU General Public License as published by the Free Software
	Foundation, either version 3 of the License, or (at your option) any later version.

	ZZACWT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
	PURPOSE. See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with ZZACWT.
	If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

//! \file mod_mixer.hpp


//! \brief Modulator/mixer class for combining the audio signal from 
//! the oscillator with noise.
//! 
//! This class takes the audio samples generated by the oscillator and
//! modulates them with the envelope generated by the shaper, and then 
//! adds noise samples.
//! 
//! The audio smaples from the shaper contain meta-data which should be
//! carried forward to the output queue. This meta-data indicates the
//! text character being transmitted at the time of the sample.
//! 
//! Audio samples will be generated on demand. When the output queue is nearly empty,
//! the modulator will combine the samples from each of the input
//! queues (oscillator, shaper, noise generator).
//! 
//! This operation shall be performed in a separate thread.

#include "zc_active_queue.h"
#include "zc_async_queue.h"

#include <queue>
#include <thread>

// Forward declarations
class oscillator;
class shaper;
class noise_gen;

class mod_mixer
{
public:
	mod_mixer(zc_active_queue<double>* oscillator_queue, 
		zc_active_queue<double>* shaper_queue, 
		zc_active_queue<double>* noise_queue, 
		zc_async_queue<double>* output_queue,
		oscillator* oscillator_ptr,
		shaper* shaper_ptr,
		noise_gen* noise_gen_ptr);
	~mod_mixer();

	//! Clear all queues and reset the internal state of the modulator/mixer
	void clear();

private:
	//! Pointers to the input and output queues
	zc_active_queue<double>* oscillator_queue_;
	zc_active_queue<double>* shaper_queue_;
	zc_active_queue<double>* noise_queue_;
	zc_async_queue<double>* output_queue_;
	//! Pointers to the producer objects for waking them up
	oscillator* oscillator_;
	shaper* shaper_;
	noise_gen* noise_gen_;
	//! Thread for the modulation/mixing process
	std::thread modulation_thread_;
	bool stop_modulation_ = false; //!< Flag to signal the modulation thread to stop
	//! Clear the internal state of the modulator/mixer, including any buffers or state variables used for modulation and mixing
	bool clear_requested_ = false;
	//! Modulation/mixing loop for the modulation thread
	static void modulation_loop(mod_mixer* mixer);

};
