/*
	Copyright 2026, Philip Rose, GM3ZZA

	This file is part of ZZACWT: ZZA CW Trainer.

	ZZACWT is free software: you can redistribute it and/or modify it under the
	terms of the Lesser GNU General Public License as published by the Free Software
	Foundation, either version 3 of the License, or (at your option) any later version.

	ZZACWT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
	PURPOSE. See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with ZZACWT.
	If not, see <https://www.gnu.org/licenses/>.
*/
#pragma once

#include "params.hpp"

#include "zc_active_queue.h"

#include <condition_variable>
#include <mutex>
#include <queue>
#include <random>
#include <string>
#include <thread>
#include <vector>

//! \file noise_gen.hpp
//! 
extern double DEFAULT_SAMPLE_RATE;

//! \brief Noise generator class for simulating various
//! types of noise and distortion in the audio signal.
//! 
//! This class generates noise samples according to the settings
//! and outputs them to an audio data queue which is consumed by the modulator.
//!
//! The types of noise that can be generated include:
//! - White noise: random samples with a flat frequency spectrum. This 
//!   will be generated by sampling from a uniform distribution 
//!   and scaling by the noise volume setting.
//! - Impact noise: random samples of white noisethat occur at random intervals, simulating
//!  the effect of lightning or other impulsive noise sources.
//!  The severity setting controls the frequency of these noise events, 
//!  and the volume setting controls the amplitude of the noise.
//! - Plinks and plonks: short bursts of tone that occur at random intervals, simulating the effect of
//!  other signal interference. The severity setting controls the frequency of these events, 
//!  and the volume setting controls the amplitude of the noise. The 
//!  pitch of the plinks and plonks is determined randomly within the typical
//! range of amateur radio frequencies (e.g. 300 Hz to 3000 Hz). The
//! duration of the tones will be set randomly between 10 ms and 100 ms.
//! 
//! White noise shall be continually generated at the specified volume level, 
//! while impact noise and plinks/plonks will occur at random intervals 
//! according to the severity setting. The noise samples will be generated in a 
//! separate thread to avoid blocking the main audio generation process. 
//! The noise generator will maintain an internal state to track when 
//! the next noise event should occur and will generate noise samples accordingly.
//! 
//! Audio smaples will be generated on demand. When the output queue is nearly empty, 
//! the noise generator will generate more noise samples based on the current settings 
//! and push them onto the queue. White noise generation will stop when an
//! upper limit on the output queue is reached. Impact and plink/plonk events
//! will complete if started but new events will not be started until 
//! the queue is again below the lower limit.
//! 
class noise_gen
{
public:
	//! Constructor. Takes the audio data queue as arguments.
	noise_gen(zc_active_queue<double>* audio_data_queue);
	//! Destructor.
	~noise_gen();

	//! Apply settings and update internal state. This will be called whenever the settings are changed by the user interface.
	void apply_settings();

	//! Clear the generation of audio samples. This will clear the output queue and reset the internal state of the noise generator to be ready for a new sequence of symbols.
	void clear();

private:
	//! Generate a single burst of impact noise. 
	//! This will consist of a short burst of white noise.
	//! \param noise An array of audio samples to which the generated noise samples will be pushed.
	void generate_impact_noise();

	//! Generate a single plink or plonk event. This will consist of a short burst of tone at a random frequency.
	//! \param noise An array of audio samples to which the generated noise samples will be pushed.
	void generate_plink_plonk();

	//! Callback function for when the audio data queue is low.
	static void cb_audio_data_queue_low(void* user_data);

	//! Pointer to the audio data queue where generated noise samples will be pushed.
	zc_active_queue<double>* audio_data_queue_;

	//! Random number generator for generating noise samples and determining when noise events occur.
	std::mt19937 rng_;
	//! Distribution for generating white noise samples.
	std::normal_distribution<double> white_noise_dist_;

	//! Distribution for determining when the next impact/plink noise event should occur based on the severity setting.
	std::exponential_distribution<double> noise_event_dist_;

	//! Disturber type for noise generation (none, impact, plink/plonk).
	disturber_type current_disturber_;
	//! Current noise volume level (0-100).
	double noise_volume_ = 0.0F;
	//! Current noise severity level (0-100).
	double noise_severity_ = 0.0F;

	//! Sample rate
	double sample_rate_ = DEFAULT_SAMPLE_RATE;

	//! Time for the next noise event to occur, in samples. 
	//! This will be updated after each noise event is generated and
	//! decremented as samples are generated to determine 
	//! when the next noise event should occur.
	int next_noise_event_time_ = 0;

};

