/*
	Copyright 2026, Philip Rose, GM3ZZA

	This file is part of ZZACWT: ZZA CW Trainer.

	ZZACWT is free software: you can redistribute it and/or modify it under the
	terms of the Lesser GNU General Public License as published by the Free Software
	Foundation, either version 3 of the License, or (at your option) any later version.

	ZZACWT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
	PURPOSE. See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with ZZACWT.
	If not, see <https://www.gnu.org/licenses/>.
*/
#pragma once

#include "params.hpp"

#include "codec.hpp"

#include "zc_async_queue.h"
#include "zc_audio_data.h"

#include <atomic>
#include <map>
#include <queue>
#include <random>
#include <string>
#include <thread>
#include <vector>

//! \file shaper.hpp

//! \brief Shaper class for generating text sequences for Morse code practice.
//! 
//! This class takes the symbols generated by the Encoder, and
//! applies timing according to the speed settings to generate the audio
//! envelope.
//! 
//! The basic unit of timing is the dot-time, which is the normal duration
//! of a dot mark. At 12 WPM, the dot-time is 100 ms.
//! 
//! The shaper receives from the encoder a sequence of dots and dashes and
//! converts this into a sequence of audio samples representing the audio envelope.
//! 
//! It first converts the dots and dashes into a sequence of symbols 
//! representing the marks and spaces of the transmitted code.
//!
//! The symbols represent either:
//! - A dot mark. The audio envelope is on for one dot-time.
//! - A dash mark. The audio envelope is on for three dot-times.
//! - An internal space. The audio envelope is off for one dot-time.
//! - A character space. The audio envelope is off for three dot-times.
//! - A word space. The audio envelope is off for seven dot-times.
//! 
//! Morse code timing is based
//! on the word "PARIS" which has a duration of 50 dot-times. 31 
//! dot-times are used for the marks and internal spaces, leaving
//! 19 dot-times for the character and word spaces.  
//! In Farnsworth mode, the character and word spaces are increased to
//! achieve the desired effective speed.
//! In Wordsworth mode, only the word spaces are increased to achieve 
//! the desired effective speed.
//! 
//! Let the effective speed be S WPM, and the character speed be C WPM. 
//! 
//! In Farnsworth mode the time allocated to the character and word spaces 
//! is increased to (60/50) * (50/S - 31/C) dot-times, while
//! the time allocated to the marks and internal spaces remains at 31 dot-times.
//! This increase is distributed between the character and word spaces 
//! in the same ratio as in normal Morse code, i.e. 3:7. 
//! In the standard word "PARIS", there are 4 character spaces and 1 word space, 
//! so the character space is 3/19 of the total space time, and the word space is 7/19 of the total space time.
//! The character space is increased to (60/50) * (50/S - 31/C) * 3/19 dot-times, and
//! the word space is increased to (60/50) * (50/S - 31/C) * 7/19 dot-times.
//! 
//! In Wordsworth the additional time is added only to the word space which
//! represents 7/50 of the total time for the word "PARIS". The word space is
//! increased to (60/50) * (50/S - 43/C) dot-times, while the character space 
//! remains unaltered.
//! 
//! With timing disturbance enabled, the symbol durations are randomly 
//! varied according to a specified distribution. Six levels of timing disturbance
//! are available:
//! 0 - No disturbance
//! 1 - The symbol duration is varied by between -2% and +5% of the nominal dot-time.
//! 2 - The symbol duration is varied by between -4% and +10% of the nominal dot-time.
//! 3 - The symbol duration is varied by between -6% and +15% of the nominal dot-time.
//! 4 - The symbol duration is varied by between -8% and +20% of the nominal dot-time.
//! 5 - The symbol duration is varied by between -10% and +25% of the nominal dot-time.
//! The distribution is non-uniform with a mean of 100%.
//!  
//! The transtion between mark and space states is smoothed by applying a raised cosine 
//! function at the end of each mark and the end of each space. 
//! The duration of the rise/fall is defined in settings (in ms) and has been
//! varied to achieve softness disturbance as necessary.

class shaper
{
public:
	//! Constructor. Takes the audio data queue as arguments.
	shaper(zc_async_queue<zc_audio_data>* audio_data_queue);
	//! Destructor.
	~shaper();
	//! Apply the current settings to update the internal state of the shaper.
	void apply_settings();
	//! Clear the generation of audio samples.
	//! This will clear the output queue and reset the internal
	//! state of the shaper to be ready for a new sequence of symbols.
	void clear();

private:
	//! Generate the audio envelope for the specified symbol. 
	//! It starts by trnsitioning from the current state (mark or space)
	//! to the new state (mark or space) using a raised cosine function 
	//! and then continues in the new state for the remaining duration of the symbol.
	//! \param symbol The symbol for which to generate the audio envelope.
	//! \param audio_samples The queue to which the generated audio samples will be pushed.
	void generate_envelope(symbol_t symbol, std::queue<float>& audio_samples);

	//! Generate timing disturbance value.
	float generate_delta_t();

	//! Add a raised cosine transition onto the specified audio sample queue.
	void add_raised_cosine(std::queue<float>& audio_samples, float duration, bool target_mark);

	//! Add an overshoot disturbance to the specified audio sample queue.
	void add_overshoot(std::queue<float>& audio_samples, float duration, bool target_mark);

	//! Current state of the shaper (mark or space)
	bool is_mark_ = false;

	//! Current dot-time duration in seconds.
	float dot_time_ = 0.1F;
	//! Timing disturbance level (0-5).
	int timing_disturbance_level_ = 0;
	//! Duration of the raised cosine transition in seconds.
	float rise_fall_time_ = 0.01F;
	//! Current speed mode (Farnsworth, Wordsworth, or normal).
	speed_type speed_mode_ = speed_type::NORMAL;
	//! Dot speed in WPM.
	float dot_speed_ = 12.0F;
	//! Overall speed in WPM for Farnsworth and Wordsworth modes.
	float overall_speed_ = 12.0F;
	//! Nominal symbol durations in seconds for the effective speed.
	std::map<symbol_t, float> symbol_durations_;

	//! Update the symbol durations based on the current speed settings.
	void update_symbol_durations();

	//! Thread for generating audio samples.
	std::thread generation_thread_;
	//! Flag to signal the generation thread to stop.
	std::atomic<bool> stop_generation_ = false;
	//! Flag to suspend and clear down the existing generated samples.
	std::atomic<bool> clear_requested_ = false;
	//! Method for the generation thread to continuously generate audio samples based on the symbol sequence and push them onto the audio data queue.
	static void generation_loop(shaper* shaper_instance);

	//! Pointer to the audio data queue.
	zc_async_queue<zc_audio_data>* audio_data_queue_;

	//! Random number generator for timing disturbance.
	std::mt19937 rng_;
	std::uniform_real_distribution<float> dist_;

	//! Test mode B - Solid tone
	bool test_mode_b_ = false;

};
